(define (problem demo)
	(:domain taxi)
	(:objects 
		player0 player1 - player
		car0 car1 - unit
		person0 person1 person2 - person
		n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 - location
		)
	(:init 
		(is-enemy player0 player1)
		(has-unit player0 car0)
		(is-enemy player1 player0)
		(has-unit player1 car1)
		
		(at car0 n0)
		(empty car0)
		(at car1 n5)
		(empty car1)
		
		(at person0 n4)
		(destination person0 n2)
		(waiting person0)
		(= (payment person0) 230)
		(at person1 n5)
		(destination person1 n2)
		(waiting person1)
		(= (payment person1) 200)
		(at person2 n0)
		(destination person2 n3)
		(waiting person2)
		(= (payment person2) 300)
		
		(connected n3 n9)
		(connected n9 n3)
		(= (distance n3 n9) 6)
		(= (distance n9 n3) 6)
		(connected n9 n7)
		(connected n7 n9)
		(= (distance n9 n7) 9)
		(= (distance n7 n9) 9)
		(connected n7 n1)
		(connected n1 n7)
		(= (distance n7 n1) 7)
		(= (distance n1 n7) 7)
		(connected n7 n2)
		(connected n2 n7)
		(= (distance n7 n2) 9)
		(= (distance n2 n7) 9)
		(connected n1 n2)
		(connected n2 n1)
		(= (distance n1 n2) 1)
		(= (distance n2 n1) 1)
		(connected n2 n0)
		(connected n0 n2)
		(= (distance n2 n0) 4)
		(= (distance n0 n2) 4)
		(connected n0 n6)
		(connected n6 n0)
		(= (distance n0 n6) 7)
		(= (distance n6 n0) 7)
		(connected n0 n5)
		(connected n5 n0)
		(= (distance n0 n5) 13)
		(= (distance n5 n0) 13)
		(connected n6 n5)
		(connected n5 n6)
		(= (distance n6 n5) 6)
		(= (distance n5 n6) 6)
		(connected n6 n4)
		(connected n4 n6)
		(= (distance n6 n4) 9)
		(= (distance n4 n6) 9)
		(connected n5 n4)
		(connected n4 n5)
		(= (distance n5 n4) 15)
		(= (distance n4 n5) 15)
		(connected n4 n8)
		(connected n8 n4)
		(= (distance n4 n8) 9)
		(= (distance n8 n4) 9)
		(connected n4 n3)
		(connected n3 n4)
		(= (distance n4 n3) 17)
		(= (distance n3 n4) 17)
		(connected n8 n3)
		(connected n3 n8)
		(= (distance n8 n3) 19)
		(= (distance n3 n8) 19)
		(connected n8 n9)
		(connected n9 n8)
		(= (distance n8 n9) 20)
		(= (distance n9 n8) 20)
		
		)
	(:goal (and 
		(preference delivered-player0-person0 (is-delivered person0 player0))
		(preference delivered-player0-person1 (is-delivered person1 player0))
		(preference delivered-player0-person2 (is-delivered person2 player0))))

	(:metric minimize (+ 
		(* 230 (is-violated delivered-player0-person0))
		(* 200 (is-violated delivered-player0-person1))
		(* 300 (is-violated delivered-player0-person2))))

	(:goal (and 
		(preference delivered-player1-person0 (is-delivered person0 player1))
		(preference delivered-player1-person1 (is-delivered person1 player1))
		(preference delivered-player1-person2 (is-delivered person2 player1))))

	(:metric minimize (+ 
		(* 230 (is-violated delivered-player1-person0))
		(* 200 (is-violated delivered-player1-person1))
		(* 300 (is-violated delivered-player1-person2))))

	