(define (problem demo)
	(:domain taxi)
	(:objects: 
		player0 player1 - player
		car0 car1 - unit
		person0 person1 person2 - person
		n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 - location
		)
	(:init 
		(is-enemy player0 player1)
		(has-unit player0 car0)
		(is-enemy player1 player0)
		(has-unit player1 car1)
		
		(at car0 n0)
		(empty car0)
		(at car1 n5)
		(empty car1)
		
		(at person0 n5)
		(destination person0 n7)
		(waiting person0)
		(= (payment person0) 150)
		(at person1 n4)
		(destination person1 n5)
		(waiting person1)
		(= (payment person1) 210)
		(at person2 n3)
		(destination person2 n0)
		(waiting person2)
		(= (payment person2) 40)
		
		(connected n9 n2)
		(connected n2 n9)
		(= (distance n9 n2) 3)
		(= (distance n2 n9) 3)
		(connected n2 n5)
		(connected n5 n2)
		(= (distance n2 n5) 8)
		(= (distance n5 n2) 8)
		(connected n5 n6)
		(connected n6 n5)
		(= (distance n5 n6) 1)
		(= (distance n6 n5) 1)
		(connected n6 n8)
		(connected n8 n6)
		(= (distance n6 n8) 5)
		(= (distance n8 n6) 5)
		(connected n6 n7)
		(connected n7 n6)
		(= (distance n6 n7) 11)
		(= (distance n7 n6) 11)
		(connected n8 n7)
		(connected n7 n8)
		(= (distance n8 n7) 7)
		(= (distance n7 n8) 7)
		(connected n7 n3)
		(connected n3 n7)
		(= (distance n7 n3) 4)
		(= (distance n3 n7) 4)
		(connected n7 n0)
		(connected n0 n7)
		(= (distance n7 n0) 5)
		(= (distance n0 n7) 5)
		(connected n3 n0)
		(connected n0 n3)
		(= (distance n3 n0) 1)
		(= (distance n0 n3) 1)
		(connected n0 n4)
		(connected n4 n0)
		(= (distance n0 n4) 1)
		(= (distance n4 n0) 1)
		(connected n0 n1)
		(connected n1 n0)
		(= (distance n0 n1) 16)
		(= (distance n1 n0) 16)
		(connected n4 n1)
		(connected n1 n4)
		(= (distance n4 n1) 17)
		(= (distance n1 n4) 17)
		(connected n4 n9)
		(connected n9 n4)
		(= (distance n4 n9) 13)
		(= (distance n9 n4) 13)
		(connected n1 n9)
		(connected n9 n1)
		(= (distance n1 n9) 16)
		(= (distance n9 n1) 16)
		(connected n1 n2)
		(connected n2 n1)
		(= (distance n1 n2) 14)
		(= (distance n2 n1) 14)
		
		)
	(:goal (and 
		(preference delivered-player0-person0 (is-delivered person0 player0))
		(preference delivered-player0-person1 (is-delivered person1 player0))
		(preference delivered-player0-person2 (is-delivered person2 player0))))

	(:metric minimize (+ 
		(* 150 (is-violated delivered-player0-person0))
		(* 210 (is-violated delivered-player0-person1))
		(* 40 (is-violated delivered-player0-person2))))

	(:goal (and 
		(preference delivered-player1-person0 (is-delivered person0 player1))
		(preference delivered-player1-person1 (is-delivered person1 player1))
		(preference delivered-player1-person2 (is-delivered person2 player1))))

	(:metric minimize (+ 
		(* 150 (is-violated delivered-player1-person0))
		(* 210 (is-violated delivered-player1-person1))
		(* 40 (is-violated delivered-player1-person2))))

	