(define (problem demo)
	(:domain taxi)
	(:objects: 
		player0 player1 - player
		car0 car1 - unit
		person0 person1 person2 - person
		n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 - location
		)
	(:init 
		(is-enemy player0 player1)
		(has-unit player0 car0)
		(is-enemy player1 player0)
		(has-unit player1 car1)
		
		(at car0 n0)
		(empty car0)
		(at car1 n5)
		(empty car1)
		
		(at person0 n8)
		(destination person0 n9)
		(waiting person0)
		(= (payment person0) 400)
		(at person1 n3)
		(destination person1 n2)
		(waiting person1)
		(= (payment person1) 130)
		(at person2 n6)
		(destination person2 n0)
		(waiting person2)
		(= (payment person2) 120)
		
		(connected n0 n6)
		(connected n6 n0)
		(= (distance n0 n6) 9)
		(= (distance n6 n0) 9)
		(connected n0 n2)
		(connected n2 n0)
		(= (distance n0 n2) 10)
		(= (distance n2 n0) 10)
		(connected n6 n2)
		(connected n2 n6)
		(= (distance n6 n2) 2)
		(= (distance n2 n6) 2)
		(connected n2 n3)
		(connected n3 n2)
		(= (distance n2 n3) 10)
		(= (distance n3 n2) 10)
		(connected n3 n7)
		(connected n7 n3)
		(= (distance n3 n7) 6)
		(= (distance n7 n3) 6)
		(connected n3 n8)
		(connected n8 n3)
		(= (distance n3 n8) 5)
		(= (distance n8 n3) 5)
		(connected n7 n8)
		(connected n8 n7)
		(= (distance n7 n8) 10)
		(= (distance n8 n7) 10)
		(connected n7 n5)
		(connected n5 n7)
		(= (distance n7 n5) 6)
		(= (distance n5 n7) 6)
		(connected n8 n5)
		(connected n5 n8)
		(= (distance n8 n5) 5)
		(= (distance n5 n8) 5)
		(connected n8 n1)
		(connected n1 n8)
		(= (distance n8 n1) 17)
		(= (distance n1 n8) 17)
		(connected n5 n1)
		(connected n1 n5)
		(= (distance n5 n1) 12)
		(= (distance n1 n5) 12)
		(connected n1 n9)
		(connected n9 n1)
		(= (distance n1 n9) 20)
		(= (distance n9 n1) 20)
		(connected n1 n4)
		(connected n4 n1)
		(= (distance n1 n4) 10)
		(= (distance n4 n1) 10)
		(connected n9 n4)
		(connected n4 n9)
		(= (distance n9 n4) 15)
		(= (distance n4 n9) 15)
		(connected n4 n0)
		(connected n0 n4)
		(= (distance n4 n0) 19)
		(= (distance n0 n4) 19)
		
		)
	(:goal (and 
		(preference delivered-player0-person0 (is-delivered person0 player0))
		(preference delivered-player0-person1 (is-delivered person1 player0))
		(preference delivered-player0-person2 (is-delivered person2 player0))))

	(:metric maximize (+ 
		(* 400 - 1 (is-violated delivered-player0-person0))
		(* 130 - 1 (is-violated delivered-player0-person1))
		(* 120 - 1 (is-violated delivered-player0-person2))))

	(:goal (and 
		(preference delivered-player1-person0 (is-delivered person0 player1))
		(preference delivered-player1-person1 (is-delivered person1 player1))
		(preference delivered-player1-person2 (is-delivered person2 player1))))

	(:metric maximize (+ 
		(* 400 - 1 (is-violated delivered-player1-person0))
		(* 130 - 1 (is-violated delivered-player1-person1))
		(* 120 - 1 (is-violated delivered-player1-person2))))

	